version: '3'

dotenv:
  - .env

# Global configuration
vars:
  PROFILE: '{{.LAB_MINIKUBE_PROFILE | default "argocd-lab"}}'
  K8S_VERSION: '{{.LAB_K8S_VERSION | default "v1.35.0"}}'
  MINIKUBE_DRIVER: '{{.LAB_MINIKUBE_DRIVER | default "docker"}}'
  ARGOCD_NAMESPACE: '{{.LAB_ARGOCD_NAMESPACE | default "argocd"}}'
  ARGOCD_PORT: '{{.LAB_ARGOCD_PORT | default 8081}}'
  ARGO_VALUES: '{{.LAB_ARGO_VALUES | default "k8s/argocd/values.yaml"}}'

# Include task modules
includes:
  lab: ./tasks/lab.yml
  argocd: ./tasks/argocd.yml
  postgres: ./tasks/postgres.yml
  airflow: ./tasks/airflow.yml
  apps: ./tasks/apps.yml
  docs: ./tasks/docs.yml
  quality: ./tasks/quality.yml
  utils: ./tasks/utils.yml

# Top-level tasks
tasks:
  default:
    desc: Show available tasks
    silent: true
    cmds:
      - task --list

  init:
    desc: "🌱  Create .env from template"
    silent: true
    cmds:
      - |
          if [ -f .env ]; then
            echo "[init] .env already exists"
          else
            cp env.example .env
            echo "[init] Created .env from env.example"
          fi

  _check-deps:
    internal: true
    silent: true
    preconditions:
      - sh: command -v kubectl
        msg: "kubectl is not installed. Run 'task utils:install' first"
      - sh: command -v helm
        msg: "helm is not installed. Run 'task utils:install' first"
      - sh: command -v minikube
        msg: "minikube is not installed. Run 'task utils:install' first"

  _check-cluster:
    internal: true
    silent: true
    preconditions:
      - sh: minikube status -p {{.PROFILE}} >/dev/null 2>&1
        msg: "Minikube cluster is not running. Run 'task lab:up' first"
