version: '3'

vars:
  PROFILE: argocd-lab
  K8S_VERSION: v1.35.0
  ARGOCD_NAMESPACE: argocd
  AIRFLOW_NAMESPACE: airflow
  ARGO_VALUES: k8s/argocd/values.yaml
  APPS_PATH: argocd/apps

tasks:
  install:
    desc: Install required tooling (macOS only, uses Homebrew)
    cmds:
      - ./scripts/install-macos.sh

  # Pre-commit tasks
  pre-commit:run:
    desc: Run pre-commit hooks on all files
    cmds:
      - pre-commit run --all-files

  pre-commit:install:
    desc: Install pre-commit hooks into git
    cmds:
      - pre-commit install

  # Docs tasks
  docs:serve:
    desc: Serve docs using uv (project-scoped in ./docs)
    cmds:
      - uv run --project docs mkdocs serve --livereload --watch docs

  docs:build:
    desc: Build docs using uv (project-scoped in ./docs)
    cmds:
      - uv run --project docs mkdocs build

  docs:clean:
    desc: Clean generated docs outputs and local virtual environments
    cmds:
      - sh -c 'rm -rf docs/site .venv docs/.venv && find docs -type d -name __pycache__ -exec rm -rf {} +'

  # Environment lifecycle
  env:start:
    desc: Start local Kubernetes (Minikube) environment
    cmds:
      - ./scripts/env-start.sh --profile {{.PROFILE}} --k8s-version {{.K8S_VERSION}}

  env:start:verbose:
    desc: Start environment with verbose output for debugging
    cmds:
      - ./scripts/env-start.sh --verbose --profile {{.PROFILE}} --k8s-version {{.K8S_VERSION}}

  env:stop:
    desc: Stop local environment (delete Minikube profile)
    cmds:
      - ./scripts/lab-stop.sh --profile {{.PROFILE}}

  # Tool deployments (require environment to be running)
  deploy:argocd:
    desc: Install/upgrade Argo CD via Helm
    cmds:
      - ./scripts/deploy-tools.sh --verbose --argocd-namespace {{.ARGOCD_NAMESPACE}} --argo-values {{.ARGO_VALUES}} --apps-path {{.APPS_PATH}}

  deploy:apps:
    desc: Apply Argo CD App of Apps (includes Airflow and backend)
    cmds:
      - ./scripts/deploy-tools.sh --argocd-namespace {{.ARGOCD_NAMESPACE}} --airflow-namespace {{.AIRFLOW_NAMESPACE}} --apps-path {{.APPS_PATH}} --argo-values {{.ARGO_VALUES}}

  lab:start:
    desc: "Convenience: start environment then deploy Argo CD + apps"
    cmds:
      - "task env:start"
      - "task deploy:argocd"
      - "task deploy:apps"

  lab:stop:
    desc: Stop lab environment
    cmds:
      - task env:stop
