version: '3'

vars:
  CLUSTER_NAME: argocd-lab
  K8S_VERSION: v1.35.0
  ARGOCD_NAMESPACE: argocd
  AIRFLOW_NAMESPACE: airflow
  KIND_CONFIG: "" # leave empty to auto-generate in lab-start.sh
  ARGO_VALUES: k8s/argocd/values.yaml
  APPS_PATH: argocd/apps

tasks:
  install:
    desc: Install required tooling (macOS only, uses Homebrew)
    cmds:
      - ./scripts/install-macos.sh

  docs:serve:
    desc: Serve docs using uv (project-scoped in ./docs)
    cmds:
      - uv run --project docs mkdocs serve --livereload --watch docs

  docs:build:
    desc: Build docs using uv (project-scoped in ./docs)
    cmds:
      - uv run --project docs mkdocs build

  docs:clean:
    desc: Clean generated docs outputs and local virtual environments
    cmds:
      - sh -c 'rm -rf docs/site .venv docs/.venv && find docs -type d -name __pycache__ -exec rm -rf {} +'

  lab:start:
    desc: Start Kind cluster and bootstrap Argo CD + Apps
    cmds:
      - ./scripts/lab-start.sh --cluster-name {{.CLUSTER_NAME}} --k8s-version {{.K8S_VERSION}} --kind-config {{.KIND_CONFIG}} --argocd-namespace {{.ARGOCD_NAMESPACE}} --airflow-namespace {{.AIRFLOW_NAMESPACE}} --argo-values {{.ARGO_VALUES}} --apps-path {{.APPS_PATH}}

  lab:stop:
    desc: Stop Kind cluster
    cmds:
      - ./scripts/teardown.sh

  argocd:port-forward:
    desc: Port-forward Argo CD server to localhost:8080
    cmds:
      - kubectl -n {{.ARGOCD_NAMESPACE}} port-forward svc/argocd-server 8080:443
