version: '3'

vars:
  PROFILE: argocd-lab
  K8S_VERSION: v1.35.0
  ARGOCD_NAMESPACE: argocd
  ARGO_VALUES: k8s/argocd/values.yaml

tasks:
  install:
    desc: Install required tooling (macOS only, uses Homebrew)
    cmds:
      - ./scripts/setup-dependencies.sh

  # Pre-commit tasks
  pre-commit:run:
    desc: Run pre-commit hooks on all files
    cmds:
      - pre-commit run --all-files

  pre-commit:install:
    desc: Install pre-commit hooks into git
    cmds:
      - pre-commit install

  # Docs tasks
  docs:serve:
    desc: Serve docs using uv (project-scoped in ./docs)
    cmds:
      - uv run --project docs mkdocs serve --livereload --watch docs

  docs:build:
    desc: Build docs using uv (project-scoped in ./docs)
    cmds:
      - uv run --project docs mkdocs build

  docs:clean:
    desc: Clean generated docs outputs and local virtual environments
    cmds:
      - sh -c 'rm -rf docs/site .venv docs/.venv && find docs -type d -name __pycache__ -exec rm -rf {} +'

  # Environment lifecycle
  env:start:
    desc: Start Minikube and deploy Argo CD
    cmds:
      - ./scripts/minikube-start.sh --profile {{.PROFILE}} --k8s-version {{.K8S_VERSION}}
      - ./scripts/argocd-deploy.sh --argocd-namespace {{.ARGOCD_NAMESPACE}} --argo-values {{.ARGO_VALUES}}

  env:start:verbose:
    desc: Start environment with verbose output for debugging
    cmds:
      - ./scripts/minikube-start.sh --verbose --profile {{.PROFILE}} --k8s-version {{.K8S_VERSION}}
      - ./scripts/argocd-deploy.sh --verbose --argocd-namespace {{.ARGOCD_NAMESPACE}} --argo-values {{.ARGO_VALUES}}

  env:stop:
    desc: Stop local environment (delete Minikube profile)
    cmds:
      - ./scripts/minikube-stop.sh --profile {{.PROFILE}}

  # Argo CD deployment (standalone)
  argocd:deploy:
    desc: Deploy Argo CD to existing Minikube cluster
    cmds:
      - ./scripts/argocd-deploy.sh --argocd-namespace {{.ARGOCD_NAMESPACE}} --argo-values {{.ARGO_VALUES}} --port {{.ARGOCD_PORT}}

  argocd:password:
    desc: Get Argo CD admin password
    cmds:
      - kubectl -n {{.ARGOCD_NAMESPACE}} get secret argocd-initial-admin-secret -o jsonpath='{.data.password}' | base64 --decode && echo

  # Convenience aliases
  lab:start:
    desc: Start lab (Minikube + Argo CD)
    cmds:
      - task env:start

  lab:stop:
    desc: Stop lab environment
    cmds:
      - task env:stop

  lab:status:
    desc: Check lab environment status
    cmds:
      - ./scripts/check-lab-status.sh
