apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: argocd
spec:
  project: default
  source:
    # Use Apache Airflow helm repository directly
    repoURL: https://airflow.apache.org
    chart: airflow
    targetRevision: 1.18.0
    helm:
      valuesObject:
        # Disable internal PostgreSQL - we use external PostgreSQL
        postgresql:
          enabled: false
        # Configure executor
        executor: CeleryExecutor
        # Webserver secret key for Flask session management (required)
        webserverSecretKey: airflow-webserver-secret
        # Webserver configuration
        webserver:
          defaultUser:
            enabled: true
            username: admin
            email: admin@example.com
            firstName: Admin
            lastName: User
            role: Admin
          service:
            type: ClusterIP
            port: 8080
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 512Mi
        # Scheduler configuration
        scheduler:
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 512Mi
        # Redis for CeleryExecutor
        redis:
          enabled: true
          resources:
            limits:
              cpu: 200m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
        # Worker configuration
        workers:
          replicas: 1
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 512Mi
        # Secret configuration - inject secrets as environment variables
        secret:
          - envName: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
            secretName: postgres-secret
            secretKey: connection-string
          - envName: _AIRFLOW_WWW_USER_PASSWORD
            secretName: airflow-webserver-secret
            secretKey: webserver-password
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
