apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow-postgresql
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/barbarosydev/argocd-lab.git
    targetRevision: feature/airflow-on-argocd
    path: k8s/airflow
    directory:
      recurse: false
      include: "postgresql*.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: airflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
