apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
spec:
  project: default
  source:
    # Use Bitnami helm repository directly
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: 17.4.3
    helm:
      valuesObject:
        # PostgreSQL Configuration
        # Passwords are managed via Kubernetes secret 'postgres-secret'
        global:
          postgresql:
            auth:
              existingSecret: postgres-secret
              secretKeys:
                adminPasswordKey: postgres-password
        # Airflow database and user configuration
        auth:
          database: airflow
          username: airflow
          existingSecret: postgres-secret
          secretKeys:
            userPasswordKey: airflow-password
        primary:
          persistence:
            enabled: true
            size: 10Gi
          resources:
            limits:
              memory: 1Gi
              cpu: 500m
            requests:
              memory: 512Mi
              cpu: 250m
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
