apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
spec:
  project: default
  source:
    # Use local chart with Bitnami dependency (pre-pulled by helm dependency update)
    repoURL: https://github.com/barbarosydev/argocd-lab.git
    targetRevision: HEAD
    path: k8s/postgres
    helm:
      valuesObject:
        # PostgreSQL Configuration
        # Passwords are managed via Kubernetes secret 'postgres-secret'
        postgresql:
          global:
            postgresql:
              auth:
                existingSecret: postgres-secret
                secretKeys:
                  adminPasswordKey: postgres-password
          # Airflow database and user configuration
          auth:
            database: airflow
            username: airflow
            existingSecret: postgres-secret
            secretKeys:
              userPasswordKey: airflow-password
          primary:
            persistence:
              enabled: true
              size: 10Gi
            resources:
              limits:
                memory: 1Gi
                cpu: 500m
              requests:
                memory: 512Mi
                cpu: 250m
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
